# MongoDB daemon (mongod) configuration file
# This will be mounted directly on the Docker container

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  # Path `/data/db` is the data path in the container which maps to `./data` in this project directory (this folder is ignored by git)
  dbPath: /data/db
  journal:
    enabled: true

# Where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# Network interfaces
net:
  port: 27017
  bindIp: 0.0.0.0
  # Setup MongoDB for SSL.  No unencrypted connections will be allowed.
  # However, this will use self-signed cert.  In production DO NOT use self-signed certificates.
  ssl:
    mode: requireSSL
    PEMKeyFile: /etc/ssl/certs/server.pem
    allowInvalidCertificates: true
    allowInvalidHostnames: true


# How the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

# Sets up MongoDB to required a login
# Be sure the set the following environment variables for the Docker container:
# - MONGO_INITDB_ROOT_USERNAME
# - MONGO_INITDB_ROOT_PASSWORD
# This will allow the
security:
  authorization: enabled
